# Generated by Django 3.0.4 on 2020-03-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_product',
            name='amount',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
