# Generated by Django 3.0.4 on 2020-03-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_store_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='location',
        ),
        migrations.AddField(
            model_name='store',
            name='latitude',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='longitude',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
