# Generated by Django 3.0.4 on 2020-03-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200324_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.CharField(default='Calle 42 sur #65a - 179', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='latitude',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='store',
            name='longitude',
            field=models.CharField(max_length=50),
        ),
    ]
