# Generated by Django 3.0.4 on 2020-03-25 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200324_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='icon',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product_report',
            name='ip',
            field=models.CharField(default='0.0.0.0', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store_report',
            name='ip',
            field=models.CharField(default='0.0.0.0', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product_report',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 18, 41, 55, 634001)),
        ),
        migrations.AlterField(
            model_name='store_report',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 18, 41, 55, 632936)),
        ),
    ]
