# Generated by Django 3.0.4 on 2020-03-25 18:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200325_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_report',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 18, 46, 39, 288553, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='store_report',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 18, 46, 39, 287532, tzinfo=utc)),
        ),
    ]
