# Generated by Django 3.0.4 on 2020-03-25 18:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200325_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_report',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='store_report',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
