# Generated by Django 3.0.4 on 2020-03-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200325_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
