# Generated by Django 3.0.4 on 2020-03-27 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200326_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='store_product',
            name='unit',
            field=models.ForeignKey(default='No especificado', on_delete=django.db.models.deletion.CASCADE, to='api.units'),
            preserve_default=False,
        ),
    ]
