# Generated by Django 3.0.4 on 2020-03-27 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200327_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store_product',
            name='unit',
        ),
    ]
