# Generated by Django 3.0.4 on 2020-03-27 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200327_1618'),
        ('api', '0012_store_product_unit'),
    ]

    operations = [
    ]
