# Generated by Django 3.0.4 on 2020-03-27 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_store_product_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store_product',
            old_name='unit',
            new_name='units',
        ),
    ]
