# Generated by Django 3.0.4 on 2020-03-27 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200327_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store_product',
            name='units',
        ),
        migrations.AddField(
            model_name='product_report',
            name='units',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='api.units'),
        ),
    ]
