# Generated by Django 3.0.4 on 2020-03-27 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200327_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_report',
            name='store',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.store'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product_report',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
    ]
