# Generated by Django 3.0.4 on 2020-04-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200327_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_product',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='store_report',
        ),
    ]
