# Generated by Django 3.0.4 on 2020-04-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_store_raiting_store_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_report',
            name='photo',
            field=models.TextField(null=True),
        ),
    ]
